version: '2'
services:
  web:
    build: .
    container_name: web_jiralo
    volumes: 
      - $PWD:/home/supjirallo
    ports:
      - "3000:3000"

  compass:
    build:
      context: .
      dockerfile: Dockerfile.compass
    volumes:
      - $PWD/style:/home/style

  mongo:
    image: mongo
    container_name: mongo_jiralo
    hostname: mongo_jiralo

